import test from 'node:test';import assert from 'node:assert/strict';
import {planMiniSentenceUpgrade,planMiniCleanup} from '../mini-imports.js';
const old={schemaVersion:2,id:'echo-import-word',source:'person',target:'人【ひと】',casualTarget:'人【ひと】',politeTarget:'人【ひと】',translationProvider:'authored-import',provenance:{project:'Minihongo',starterVersion:2,path:'data/words.csv'},echoCount:9,srs:{reps:4,due:'2027-01-01'},reviews:[{rating:3}],createdAt:'2026-01-01'};
const next={...old,id:'echo-import-example',source:'Who is that person?',target:'あの人【ひと】は誰【だれ】？',casualTarget:'あの人【ひと】は誰【だれ】？',provenance:{...old.provenance,starterVersion:3},srs:undefined,echoCount:0};
const backup={title:'Mini Hongo starter library',starterVersion:3,sentences:[next],replacesWordCards:[{oldId:old.id,newId:next.id,oldTarget:'人'}]};
test('sentence reimport replaces old word cards and transfers progress',()=>{const personal={...old,id:'personal'},plan=planMiniSentenceUpgrade([personal,old],backup);assert.equal(plan.removed.length,1);assert.equal(plan.sentences.length,2);assert.deepEqual(plan.sentences[0],personal);const s=plan.sentences[1];assert.equal(s.target,next.target);assert.deepEqual(s.srs,old.srs);assert.deepEqual(s.reviews,old.reviews);assert.equal(s.echoCount,9);assert.equal(planMiniSentenceUpgrade(plan.sentences,backup).sentences.length,2)});
test('edited imports and personal lookalikes are never removed',()=>{for(const card of [{...old,casualTarget:'別の文です。'},{...old,translationProvider:'google'},{...old,provenance:{...old.provenance,path:'other.csv'}}])assert.equal(planMiniSentenceUpgrade([card],backup).removed.length,0)});
test('existing example keeps its own progress instead of being overwritten',()=>{const existing={...next,id:'personal-example',echoCount:33};const plan=planMiniSentenceUpgrade([old,existing],backup);assert.equal(plan.sentences.length,1);assert.equal(plan.sentences[0].id,existing.id);assert.equal(plan.sentences[0].echoCount,33)});
test('version-3 imports are not mistaken for oversized legacy cards',()=>{assert.equal(planMiniCleanup([next]).removed.length,0)});
