import test from 'node:test';import assert from 'node:assert/strict';import {planMiniCleanup,repairMiniImport} from '../mini-imports.js';
const mine=Array.from({length:64},(_,i)=>({id:'personal-'+i,source:'My '+i,target:'日本語'+i,echoCount:i,srs:{reps:i,due:'2027-01-01'},reviews:[{at:'2026-01-01'}],grammar:['を','minihongo:gram-1'],vocabulary:[123,-1]}));
const imported={id:'echo-import-old',translationProvider:'authored-import',provenance:{project:'Minihongo'},target:mine[0].target};const catalogues={words:[{id:-1,origin:'minihongo'},{id:-2,origin:'other'}],grammar:[{id:'minihongo:gram-1',origin:'minihongo'}]};
test('removes oversized starter cards while preserving all 64 original cards and reviews',()=>{const plan=planMiniCleanup([...mine,imported],catalogues);assert.equal(plan.kept.length,64);assert.deepEqual(plan.removed,[imported]);for(let i=0;i<64;i++){assert.equal(plan.kept[i].id,mine[i].id);assert.equal(plan.kept[i].target,mine[i].target);assert.deepEqual(plan.kept[i].srs,mine[i].srs);assert.deepEqual(plan.kept[i].reviews,mine[i].reviews);assert.equal(plan.kept[i].echoCount,i)}assert.deepEqual(plan.kept[0].grammar,['を']);assert.deepEqual(plan.kept[0].vocabulary,[123]);assert.deepEqual(plan.catalogues.words,[{id:-2,origin:'other'}])});
test('never removes compact imports, personal lookalikes or Anki imports',()=>{const cards=[{...imported,id:'mine'},{...imported,provenance:{project:'Anki'}},{...imported,provenance:{project:'Minihongo',starterVersion:2}},{...imported,translationProvider:'google'}];assert.equal(planMiniCleanup(cards).kept.length,4)});
test('cleanup commits its recovery copy before deleting anything',async()=>{const seen=[];await repairMiniImport([...mine,imported],catalogues,{archive:async b=>{assert.deepEqual(b.sentences,[imported]);seen.push('archive')},replace:async b=>{assert.equal(b.length,64);seen.push('replace')},saveCatalogues:async()=>seen.push('catalogues')});assert.deepEqual(seen,['archive','replace','catalogues'])});
test('a failed recovery write cannot delete the library',async()=>{await assert.rejects(()=>repairMiniImport([...mine,imported],catalogues,{archive:async()=>{throw Error('disk full')},replace:async()=>assert.fail('must not delete'),saveCatalogues:async()=>assert.fail('must not change definitions')}),/disk full/)});
test('running the cleanup plan twice is a no-op',()=>{const first=planMiniCleanup([...mine,imported],catalogues);const second=planMiniCleanup(first.kept,first.catalogues);assert.equal(second.changed,false);assert.deepEqual(second.kept,first.kept)});

test('removes only imported grammar evidence from personal cards',()=>{const card={...mine[0],grammarAnalysis:[{text:'日本語',grammar:['を','minihongo:gram-1'],spans:[{id:'を',quote:'を'},{id:'minihongo:gram-1',quote:'日本語'}]}]};const plan=planMiniCleanup([card,imported],catalogues);assert.deepEqual(plan.kept[0].grammarAnalysis,[{text:'日本語',grammar:['を'],spans:[{id:'を',quote:'を'}]}])});
