import test from 'node:test';import assert from 'node:assert/strict';
import {fetchReference,mergeReferences,referenceKey,missingReferenceCandidates} from '../references.js';import {mergeCatalogues} from '../catalogues.js';
const entry={id:referenceKey('grammar','ざる'),kind:'grammar',term:'ざる',text:'Negative auxiliary',sourceUrl:'https://en.wiktionary.org/wiki/ざる#Japanese',sourceLabel:'Wiktionary'};
test('custom references survive catalogue backup merges and deduplicate without removing old catalogues',()=>{const original={words:[],grammar:[],references:[entry]};assert.deepEqual(mergeCatalogues(original,original),original);assert.deepEqual(mergeCatalogues(original,{words:[],grammar:[]}),original);assert.equal(mergeReferences([entry],[{...entry,text:'Updated definition'}])[0].text,'Updated definition')});
test('untrusted reference links and malformed imported data are rejected',()=>{for(const invalid of [{...entry,sourceUrl:'javascript:alert(1)'},{...entry,sourceUrl:'https://evil.example/wiki'},{...entry,id:'mismatch'},{...entry,kind:'made-up'},{...entry,text:''}])assert.equal(mergeReferences([],[invalid]).length,0)});
test('missing sentence terms keep compounds intact and skip known dictionary words and saved references',()=>{const text='鬱とクラウドネイティブと学校';const spans=[{id:1,start:text.indexOf('学校'),end:text.length}];const result=missingReferenceCandidates(text,{spans,knownKanji:c=>'学校'.includes(c)});assert.ok(result.some(r=>r.kind==='kanji'&&r.term==='鬱'));assert.ok(result.some(r=>r.term==='クラウドネイティブ'));assert.ok(!result.some(r=>r.term==='学校'));assert.ok(!missingReferenceCandidates('鬱',{references:[{kind:'kanji',term:'鬱'},{kind:'word',term:'鬱'}]}).length)});
test('kanji lookup imports source meanings and readings with attribution',async()=>{const result=await fetchReference({kind:'kanji',term:'鬱'},{fetchImpl:async(url,options)=>{assert.equal(options.credentials,'omit');assert.match(url,/kanji\//);return {ok:true,json:async()=>({kanji:'鬱',meanings:['gloom'],on_readings:['ウツ'],kun_readings:['うっ.する'],stroke_count:29})}},now:()=> '2026-10-07'});assert.match(result.text,/gloom/);assert.match(result.text,/ウツ/);assert.equal(result.fetchedAt,'2026-10-07');assert.equal(result.id,referenceKey('kanji','鬱'))});
test('word and grammar online lookups request Japanese entries with anonymous CORS and keep source URLs',async()=>{for(const kind of ['word','grammar']){const result=await fetchReference({kind,term:'ざる'},{fetchImpl:async url=>{const parsed=new URL(url);assert.equal(parsed.searchParams.get('origin'),'*');assert.equal(parsed.searchParams.get('page'),'ざる');return {ok:true,json:async()=>({parse:{title:'ざる',text:'<h2>Japanese</h2>'}})}},extractText:()=> 'Negative auxiliary'});assert.equal(result.kind,kind);assert.match(result.sourceUrl,/wiktionary/);assert.equal(result.text,'Negative auxiliary')}});
test('missing definitions and network errors never produce a saved reference',async()=>{await assert.rejects(fetchReference({kind:'word',term:'missing'},{fetchImpl:async()=>({ok:true,json:async()=>({error:{code:'missingtitle'}})})}),/No dictionary entry/);await assert.rejects(fetchReference({kind:'kanji',term:'学校'}),/exactly one/);await assert.rejects(fetchReference({kind:'word',term:'猫'},{fetchImpl:async()=>({ok:false,status:503})}),/503/)});

import {customReferenceSpans} from '../references.js';import{setImportedGrammar,point}from'../grammar.js';
test('saved compound references underline the whole term and take precedence over shorter terms',()=>{const long={...entry,id:referenceKey('word','話し合う'),kind:'word',term:'話し合う'},short={...entry,id:referenceKey('word','話'),kind:'word',term:'話'};assert.deepEqual(customReferenceSpans('話し合う',[short,long]).map(span=>[span.start,span.end,span.referenceId]),[[0,4,long.id]])});
test('saved custom grammar is available in the regular grammar index',()=>{const custom={id:entry.id,title:entry.term,level:'Custom',hint:entry.text,origin:'custom'};setImportedGrammar([custom]);assert.deepEqual(point(custom.id),custom);setImportedGrammar()});
