import test from 'node:test';import assert from 'node:assert/strict';
import {fetchReference,mergeReferences,referenceKey,missingReferenceCandidates} from '../references.js';import {mergeCatalogues} from '../catalogues.js';
const entry={id:referenceKey('grammar','ざる'),kind:'grammar',term:'ざる',text:'Negative auxiliary',sourceUrl:'https://en.wiktionary.org/wiki/ざる#Japanese',sourceLabel:'Wiktionary'};
test('custom references survive catalogue backup merges and deduplicate without removing old catalogues',()=>{const original={words:[],grammar:[],references:[entry]};assert.deepEqual(mergeCatalogues(original,original),original);assert.deepEqual(mergeCatalogues(original,{words:[],grammar:[]}),original);assert.equal(mergeReferences([entry],[{...entry,text:'Updated definition'}])[0].text,'Updated definition')});
test('untrusted reference links and malformed imported data are rejected',()=>{for(const invalid of [{...entry,sourceUrl:'javascript:alert(1)'},{...entry,sourceUrl:'https://evil.example/wiki'},{...entry,id:'mismatch'},{...entry,kind:'made-up'},{...entry,text:''}])assert.equal(mergeReferences([],[invalid]).length,0)});
test('missing sentence terms keep compounds intact and skip known dictionary words and saved references',()=>{const text='鬱とクラウドネイティブと学校';const spans=[{id:1,start:text.indexOf('学校'),end:text.length}];const result=missingReferenceCandidates(text,{spans,knownKanji:c=>'学校'.includes(c)});assert.ok(result.some(r=>r.kind==='kanji'&&r.term==='鬱'));assert.ok(result.some(r=>r.term==='クラウドネイティブ'));assert.ok(!result.some(r=>r.term==='学校'));assert.ok(!missingReferenceCandidates('鬱',{references:[{kind:'kanji',term:'鬱'},{kind:'word',term:'鬱'}]}).length)});
test('kanji lookup imports source meanings and readings with attribution',async()=>{const result=await fetchReference({kind:'kanji',term:'鬱'},{fetchImpl:async(url,options)=>{assert.equal(options.credentials,'omit');assert.match(url,/kanji\//);return {ok:true,json:async()=>({kanji:'鬱',meanings:['gloom'],on_readings:['ウツ'],kun_readings:['うっ.する'],stroke_count:29})}},now:()=> '2026-10-07'});assert.match(result.text,/gloom/);assert.match(result.text,/ウツ/);assert.equal(result.fetchedAt,'2026-10-07');assert.equal(result.id,referenceKey('kanji','鬱'))});
test('word and grammar online lookups request Japanese entries with anonymous CORS and keep source URLs',async()=>{for(const kind of ['word','grammar']){const result=await fetchReference({kind,term:'ざる'},{fetchImpl:async url=>{const parsed=new URL(url);assert.equal(parsed.searchParams.get('origin'),'*');assert.equal(parsed.searchParams.get('page'),'ざる');return {ok:true,json:async()=>({parse:{title:'ざる',text:'<h2>Japanese</h2>'}})}},extractText:()=> 'Negative auxiliary'});assert.equal(result.kind,kind);assert.match(result.sourceUrl,/wiktionary/);assert.equal(result.text,'Negative auxiliary')}});
test('missing definitions and network errors never produce a saved reference',async()=>{await assert.rejects(fetchReference({kind:'word',term:'missing'},{fetchImpl:async()=>({ok:true,json:async()=>({error:{code:'missingtitle'}})})}),/No dictionary entry/);await assert.rejects(fetchReference({kind:'kanji',term:'学校'}),/exactly one/);await assert.rejects(fetchReference({kind:'word',term:'猫'},{fetchImpl:async()=>({ok:false,status:503})}),/503/)});

import {customReferenceSpans} from '../references.js';import{setImportedGrammar,point}from'../grammar.js';
test('saved compound references underline the whole term and take precedence over shorter terms',()=>{const long={...entry,id:referenceKey('word','話し合う'),kind:'word',term:'話し合う'},short={...entry,id:referenceKey('word','話'),kind:'word',term:'話'};assert.deepEqual(customReferenceSpans('話し合う',[short,long]).map(span=>[span.start,span.end,span.referenceId]),[[0,4,long.id]])});
test('saved custom grammar is available in the regular grammar index',()=>{const custom={id:entry.id,title:entry.term,level:'Custom',hint:entry.text,origin:'custom'};setImportedGrammar([custom]);assert.deepEqual(point(custom.id),custom);setImportedGrammar()});

import {validateLookupPlan,resolveReferenceLookup} from '../references.js';
const plan=(surface,term,extra={})=>({surface,candidates:[{kind:'word',term,explanation:'Past passive form',requiresConfirmation:false,...extra}]});
test('AI resolves inflected input and checks bundled dictionary before making network requests',async()=>{let fetched=false;const results=await resolveReferenceLookup({surface:'聞かれた',context:'名前を聞かれた。'},{ask:async text=>{assert.equal(JSON.parse(text).context,'名前を聞かれた。');return plan('聞かれた','聞く')},knownWords:[{w:'聞く',r:'きく',en:['hear; ask']}],lookup:async()=>{fetched=true;throw Error('should not fetch')}});assert.equal(fetched,false);assert.equal(results[0].entry.term,'聞く');assert.match(results[0].entry.text,/きく/)});
test('ambiguous spellings remain separate suggestions requiring confirmation',async()=>{const raw={surface:'時かれた',candidates:[{kind:'word',term:'聞く',explanation:'Possible typo for 聞かれた',requiresConfirmation:true},{kind:'word',term:'書く',explanation:'Possible typo for 書かれた',requiresConfirmation:true}]};const results=await resolveReferenceLookup({surface:'時かれた'},{ask:async()=>raw,knownWords:[{w:'聞く',r:'きく',en:['ask']},{w:'書く',r:'かく',en:['write']}],lookup:async()=>{throw Error('missing')}});assert.equal(results.length,2);assert.ok(results.every(r=>r.candidate.requiresConfirmation));});
test('software gate rejects malformed model forms and surface changes before lookup',async()=>{for(const raw of [plan('different','聞く'),plan('聞かれた','<script>'),plan('聞かれた','聞く',{kind:'bad'}),plan('聞かれた','聞く',{requiresConfirmation:'yes'})])assert.throws(()=>validateLookupPlan(raw,'聞かれた'));let called=false;await assert.rejects(resolveReferenceLookup({surface:'聞かれた'},{ask:async()=>plan('changed','聞く'),lookup:async()=>{called=true}}));assert.equal(called,false)});
test('unverified suggestions and source mismatches cannot become saveable entries',async()=>{const results=await resolveReferenceLookup({surface:'聞かれた'},{ask:async()=>plan('聞かれた','聞く'),lookup:async()=>entry});assert.ok(results[0].error);assert.equal(results[0].entry,undefined)});
test('AI recognizes modified grammar and looks up its canonical construction',async()=>{const results=await resolveReferenceLookup({surface:'食べざるを得なかった',kind:'auto'},{ask:async()=>plan('食べざるを得なかった','ざる',{kind:'grammar',explanation:'Negative obligation construction'}),lookup:async()=>entry});assert.equal(results[0].entry.kind,'grammar')});
test('saved inflected forms stay tappable offline without changing their canonical identity',()=>{const saved={...entry,kind:'word',term:'聞く',id:referenceKey('word','聞く'),forms:['聞かれた']};assert.equal(customReferenceSpans('名前を聞かれた。',[saved])[0].referenceId,saved.id);assert.equal(mergeReferences([],[{...saved,forms:['']}]).length,0)});
