import {createSentence,exportBackup,mergeSentences,rubyHtml} from "./core.js";
import {deleteSentence,listSentences,replaceAll,saveSentence} from "./db.js";
import {translate} from "./api.js";
import {japaneseVoices,recognitionFactory,ShadowLoop} from "./speech.js";
import {downloadAnkiDeck} from "./anki-export.js";
const $=selector=>document.querySelector(selector);
const settings=JSON.parse(localStorage.getItem("jp-echo-settings")||"{}");
let current=null,voices=[],installPrompt=null;
const loop=new ShadowLoop({onEcho:async()=>{if(!current)return;current.echoCount++;current.updatedAt=new Date().toISOString();await saveSentence(current);renderCount()},onState:state=>{const button=$("#play-pause");$("#loop-state").textContent=({speaking:"Listen…",imitate:"Your turn—echo it.",paused:"Paused",stopped:"Ready",error:"Speech could not be played."})[state]||state;button.textContent=state==="paused"?"Play":state==="stopped"||state==="error"?"Play":"Pause";button.setAttribute("aria-pressed",String(state!=="stopped"&&state!=="error"))}});
function saveSettings(){settings.apiKey=$("#api-key").value.trim();settings.proxyUrl=$("#proxy-url").value.trim();settings.voice=$("#voice").value;settings.rate=Number($("#rate").value);settings.showEnglish=$("#show-english").checked;settings.showFurigana=$("#show-furigana").checked;settings.showPolite=$("#show-polite").checked;localStorage.setItem("jp-echo-settings",JSON.stringify(settings))}
function resetSettingsForm(){$("#api-key").value=settings.apiKey||"";$("#proxy-url").value=settings.proxyUrl||""}
function openSettings(){resetSettingsForm();updateInstallUI();$("#settings-dialog").showModal()}
function cancelSettings(){resetSettingsForm();$("#settings-dialog").close()}
function isInstalled(){return window.matchMedia("(display-mode: standalone)").matches||window.navigator.standalone===true}
function updateInstallUI(){const installed=isInstalled();$("#install-app").disabled=installed;$("#install-app").textContent=installed?"JP Echo is installed":"Install JP Echo";$("#install-status").textContent=installed?"Opened as an installed app.":""}
async function installApp(){if(isInstalled())return updateInstallUI();if(installPrompt){installPrompt.prompt();const choice=await installPrompt.userChoice;installPrompt=null;$("#install-status").textContent=choice.outcome==="accepted"?"Installation started.":"Installation was cancelled.";return updateInstallUI()}$("#install-status").textContent=/iphone|ipad|ipod/i.test(navigator.userAgent)?"In Safari, tap Share, then Add to Home Screen.":"Open the browser menu and choose Install app or Add to Home screen."}
function renderCount(){$("#echo-count").textContent=current?.echoCount??0}
function selectedJapanese(){const polite=$("#show-polite").checked;return polite?(current.politeJapanese||current.japanese):(current.casualJapanese||current.japanese)}
function selectedPlainJapanese(){const polite=$("#show-polite").checked;return polite?(current.plainPoliteJapanese||current.plainJapanese):(current.plainCasualJapanese||current.plainJapanese)}
function resetSession(){loop.stop()}
function renderSentence(){const panel=$("#practice");panel.hidden=!current;$("#welcome").hidden=!!current;if(!current)return;$("#japanese").innerHTML=rubyHtml(selectedJapanese());$("#english-display").textContent=current.english;$("#english-display").hidden=!$("#show-english").checked;panel.classList.toggle("hide-furigana",!$("#show-furigana").checked);renderCount();populateVoices()}
function openSentence(sentence){resetSession();current=sentence;$("#english-input").value=sentence.english;showView("main");renderSentence()}
function showView(name){if(name==="history")resetSession();$("#main-view").hidden=name!=="main";$("#history-view").hidden=name!=="history";$("#history-button").setAttribute("aria-pressed",String(name==="history"));if(name==="history")renderHistory()}
const escapeText=value=>{const node=document.createElement("span");node.textContent=value;return node.innerHTML};
const formatDate=value=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value));
async function renderHistory(){const items=await listSentences(),list=$("#history-list");list.replaceChildren();$("#empty-history").hidden=items.length>0;for(const item of items){const li=document.createElement("li");li.innerHTML='<button class="history-open"><span lang="ja">'+rubyHtml(item.japanese)+"</span><span>"+escapeText(item.english)+"</span><small>"+item.echoCount+" echoes · "+formatDate(item.createdAt)+'</small></button><button class="delete" aria-label="Delete sentence">×</button>';li.querySelector(".history-open").onclick=()=>openSentence(item);li.querySelector(".delete").onclick=async event=>{event.stopPropagation();if(confirm("Delete this sentence?")){await deleteSentence(item.id);if(current?.id===item.id)current=null;renderHistory()}};list.append(li)}}
async function performTranslation(){const english=$("#english-input").value.trim();if(!english)return setStatus("Enter an English sentence.",true);saveSettings();if(!settings.apiKey){setStatus("Add your DeepSeek API key in Settings.",true);return openSettings()}const button=$("#translate"),label=button.textContent;button.disabled=true;button.textContent="Translating…";button.setAttribute("aria-busy","true");setStatus("Translating…");try{const japanese=await translate(english,settings);resetSession();current=createSentence(english,japanese);await saveSentence(current);renderSentence();setStatus("Ready to practice.")}catch(error){setStatus(error.message||"Translation failed.",true)}finally{button.disabled=false;button.textContent=label;button.removeAttribute("aria-busy")}}
function setStatus(message,error=false){$("#status").textContent=message;$("#status").classList.toggle("error",error)}
function populateVoices(){voices=japaneseVoices();const select=$("#voice"),previous=settings.voice;select.replaceChildren(...voices.map((voice,index)=>{const option=new Option(voice.name+" ("+voice.lang+")",String(index));option.selected=previous===String(index);return option}));$("#voice-warning").hidden=voices.length>0;$("#play-pause").disabled=voices.length===0||!current}
function setupRecognition(){const recognition=recognitionFactory(),mic=$("#microphone");if(!recognition){mic.disabled=true;$("#voice-input-status").textContent="Voice input is unavailable in this browser. You can still type.";return}mic.onclick=()=>{$("#voice-input-status").textContent="Listening…";mic.classList.add("listening");try{recognition.start()}catch{}};recognition.onresult=event=>{$("#english-input").value=event.results[0][0].transcript;$("#voice-input-status").textContent="Transcript ready—check it, then translate."};recognition.onerror=event=>{const messages={"not-allowed":"Microphone permission is blocked. Enable it in your browser settings.","no-speech":"No speech was detected. Try again or type your sentence.","audio-capture":"No microphone is available."};$("#voice-input-status").textContent=messages[event.error]||"Voice input failed: "+event.error+"."};recognition.onend=()=>mic.classList.remove("listening")}
async function exportHistory(){const data=exportBackup(await listSentences(),settings),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),link=Object.assign(document.createElement("a"),{href:url,download:"jp-echo-backup.json"});link.click();URL.revokeObjectURL(url)}
async function exportAnki(){const button=$("#export-anki"),items=await listSentences();button.disabled=true;button.textContent="Building deck…";$("#anki-status").textContent="Creating JP Echo.apkg on this device…";try{await downloadAnkiDeck(items);$("#anki-status").textContent="JP Echo.apkg downloaded. Tap the completed download to import it directly into Anki.";$("#open-anki").hidden=false}catch(error){$("#anki-status").textContent=error.message||"Anki export failed."}finally{button.disabled=false;button.textContent="Export to Anki"}}
function openAnki(){const android=/android/i.test(navigator.userAgent),ios=/iphone|ipad|ipod/i.test(navigator.userAgent);if(android)window.location.href="intent:#Intent;package=com.ichi2.anki;end";else if(ios)window.location.href="anki://";else $("#anki-status").textContent="Open JP Echo.apkg from your Downloads folder to import it into Anki."}
async function importHistory(file){if(!file)return;try{const backup=JSON.parse(await file.text());if(backup.schemaVersion!==1||!Array.isArray(backup.sentences))throw new Error("Unsupported backup.");const merged=mergeSentences(await listSentences(),backup.sentences);await replaceAll(merged);setStatus("Imported "+backup.sentences.length+" sentence(s).");renderHistory()}catch(error){setStatus(error.message||"Import failed.",true)}}
$("#history-button").onclick=()=>showView($("#history-view").hidden?"history":"main");$("#back").onclick=()=>showView("main");$("#translate").onclick=performTranslation;$("#english-input").onkeydown=event=>{if((event.metaKey||event.ctrlKey)&&event.key==="Enter")performTranslation()};$("#play-pause").onclick=()=>{if(!current)return;if(loop.running){loop.togglePause();return}const voice=voices[Number($("#voice").value)]||voices[0];loop.play(selectedPlainJapanese(),{voice,rate:Number($("#rate").value)})};$("#show-english").onchange=()=>{saveSettings();renderSentence()};$("#show-furigana").onchange=()=>{saveSettings();renderSentence()};$("#show-polite").onchange=()=>{resetSession();saveSettings();renderSentence()};$("#voice").onchange=saveSettings;$("#rate").oninput=()=>{const rate=Number($("#rate").value);$("#rate-value").textContent=rate.toFixed(1)+"×";resetSession();loop.setRate(rate);saveSettings()};$("#settings-button").onclick=()=>$("#settings-dialog").showModal();$("#close-settings").onclick=()=>{saveSettings();$("#settings-dialog").close()};$("#export-anki").onclick=exportAnki;$("#open-anki").onclick=openAnki;$("#export").onclick=exportHistory;$("#import").onclick=()=>$("#import-file").click();$("#import-file").onchange=event=>importHistory(event.target.files[0]);
$("#settings-button").onclick=openSettings;$("#dismiss-settings").onclick=cancelSettings;$("#cancel-settings").onclick=cancelSettings;$("#install-app").onclick=installApp;$("#settings-dialog").addEventListener("cancel",resetSettingsForm);$("#settings-dialog").onclick=event=>{if(event.target===$("#settings-dialog"))cancelSettings()};$("#voice").onchange=()=>{resetSession();saveSettings()};window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;updateInstallUI()});window.addEventListener("appinstalled",()=>{installPrompt=null;updateInstallUI()});
$("#api-key").value=settings.apiKey||"";$("#proxy-url").value=settings.proxyUrl||"";$("#rate").value=settings.rate||1;$("#rate-value").textContent=Number($("#rate").value).toFixed(1)+"×";$("#show-english").checked=settings.showEnglish??false;$("#show-furigana").checked=settings.showFurigana??true;$("#show-polite").checked=settings.showPolite??false;speechSynthesis.onvoiceschanged=populateVoices;populateVoices();setupRecognition();updateInstallUI();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");
