import {createSentence,exportBackup,mergeSentences,rubyHtml} from "./core.js";
import {deleteSentence,listSentences,replaceAll,saveSentence} from "./db.js";
import {translate} from "./api.js";
import {japaneseVoices,recognitionFactory,ShadowLoop} from "./speech.js";
import {downloadAnkiDeck} from "./anki-export.js";
import {dueSentences,ensureSchedule,reviewSentence} from "./srs.js";
const $=selector=>document.querySelector(selector);
const settings=JSON.parse(localStorage.getItem("jp-echo-settings")||"{}");
let current=null,voices=[],installPrompt=null,reviewQueue=[],reviewIndex=0,reviewRevealed=false;
const loop=new ShadowLoop({onEcho:async()=>{const reviewing=!$("#review-view").hidden,target=reviewing?reviewQueue[reviewIndex]:current;if(!target)return;target.echoCount=(Number(target.echoCount)||0)+1;target.updatedAt=new Date().toISOString();await saveSentence(target);if(reviewing){reviewQueue[reviewIndex]=target;$("#review-echo-count").textContent=String(target.echoCount)}if(current?.id===target.id){current=target;renderCount()}},onState:state=>{const label=({speaking:"Listen…",imitate:"Your turn—echo it.",paused:"Paused",stopped:"Ready",error:"Speech could not be played."})[state]||state,playing=state!=="stopped"&&state!=="error",text=state==="paused"?"Play":playing?"Pause":"Play";$("#loop-state").textContent=label;$("#review-loop-state").textContent=label;for(const button of [$("#play-pause"),$("#review-audio")]){button.textContent=text;button.setAttribute("aria-pressed",String(playing))}}});
function saveSettings(){settings.apiKey=$("#api-key").value.trim();settings.proxyUrl=$("#proxy-url").value.trim();settings.voice=$("#voice").value;settings.rate=Number($("#rate").value);settings.showEnglish=$("#show-english").checked;settings.showFurigana=$("#show-furigana").checked;settings.showPolite=$("#show-polite").checked;localStorage.setItem("jp-echo-settings",JSON.stringify(settings))}
function resetSettingsForm(){$("#api-key").value=settings.apiKey||"";$("#proxy-url").value=settings.proxyUrl||"";$("#voice").value=settings.voice||"0";$("#rate").value=settings.rate||1;$("#rate-value").textContent=Number($("#rate").value).toFixed(1)+"×"}
function openSettings(){resetSettingsForm();updateInstallUI();$("#settings-dialog").showModal()}
function cancelSettings(){resetSettingsForm();$("#settings-dialog").close()}
function isInstalled(){return window.matchMedia("(display-mode: standalone)").matches||window.navigator.standalone===true}
function updateInstallUI(){const installed=isInstalled();$("#install-app").disabled=installed;$("#install-app").textContent=installed?"JP Echo is installed":"Install JP Echo";$("#install-status").textContent=installed?"Opened as an installed app.":""}
async function installApp(){if(isInstalled())return updateInstallUI();if(installPrompt){installPrompt.prompt();const choice=await installPrompt.userChoice;installPrompt=null;$("#install-status").textContent=choice.outcome==="accepted"?"Installation started.":"Installation was cancelled.";return updateInstallUI()}$("#install-status").textContent=/iphone|ipad|ipod/i.test(navigator.userAgent)?"In Safari, tap Share, then Add to Home Screen.":"Open the browser menu and choose Install app or Add to Home screen."}
function renderCount(){$("#echo-count").textContent=current?.echoCount??0}
function selectedJapanese(){const polite=$("#show-polite").checked;return polite?(current.politeJapanese||current.japanese):(current.casualJapanese||current.japanese)}
function selectedPlainJapanese(){const polite=$("#show-polite").checked;return polite?(current.plainPoliteJapanese||current.plainJapanese):(current.plainCasualJapanese||current.plainJapanese)}
function resetSession(){loop.stop()}
function renderSentence(){const panel=$("#practice");panel.hidden=!current;$("#welcome").hidden=!!current;if(!current)return;$("#japanese").innerHTML=rubyHtml(selectedJapanese());$("#english-display").textContent=current.english;$("#english-display").hidden=!$("#show-english").checked;panel.classList.toggle("hide-furigana",!$("#show-furigana").checked);renderCount();populateVoices()}
function openSentence(sentence){resetSession();current=sentence;$("#english-input").value=sentence.english;showView("main");renderSentence()}
function showView(name){if(name!=="main")resetSession();speechSynthesis.cancel();$("#main-view").hidden=name!=="main";$("#history-view").hidden=name!=="history";$("#review-view").hidden=name!=="review";$("#history-button").setAttribute("aria-pressed",String(name==="history"||name==="review"));if(name==="history")renderHistory()}
const escapeText=value=>{const node=document.createElement("span");node.textContent=value;return node.innerHTML};
const formatDate=value=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value));
async function renderHistory(){const all=await listSentences(),list=$("#history-list"),due=dueSentences(all),query=$("#history-search").value.trim().toLocaleLowerCase(),filter=$("#history-filter").value,order=$("#history-order").value,now=Date.now();let items=all.filter(item=>{const haystack=[item.english,item.japanese,item.plainJapanese,item.casualJapanese,item.politeJapanese].filter(Boolean).join(" ").toLocaleLowerCase();if(query&&!haystack.includes(query))return false;const state=item.srs?.state??0;if(filter==="due")return !item.srs?.due||Date.parse(item.srs.due)<=now;if(filter==="new")return state===0;if(filter==="learning")return state===1||state===3;if(filter==="review")return state===2;return true});const comparators={newest:(a,b)=>b.createdAt.localeCompare(a.createdAt),oldest:(a,b)=>a.createdAt.localeCompare(b.createdAt),echoes:(a,b)=>(Number(b.echoCount)||0)-(Number(a.echoCount)||0),due:(a,b)=>Date.parse(a.srs?.due||a.createdAt)-Date.parse(b.srs?.due||b.createdAt)};items.sort(comparators[order]||comparators.newest);list.replaceChildren();$("#empty-history").hidden=all.length>0;$("#empty-results").hidden=all.length===0||items.length>0;$("#due-count").textContent=String(due.length);$("#start-review").disabled=due.length===0;for(const item of items){const li=document.createElement("li");li.innerHTML='<button class="history-open"><span lang="ja">'+rubyHtml(item.japanese)+"</span><span>"+escapeText(item.english)+"</span><small>"+item.echoCount+" echoes · "+formatDate(item.createdAt)+'</small></button><button class="delete" aria-label="Delete sentence">×</button>';li.querySelector(".history-open").onclick=()=>openSentence(item);li.querySelector(".delete").onclick=async event=>{event.stopPropagation();if(confirm("Delete this sentence?")){await deleteSentence(item.id);if(current?.id===item.id)current=null;renderHistory()}};list.append(li)}}
async function performTranslation(){const english=$("#english-input").value.trim();if(!english)return setStatus("Enter an English sentence.",true);saveSettings();if(!settings.apiKey){setStatus("Add your DeepSeek API key in Settings.",true);return openSettings()}const button=$("#translate"),label=button.textContent;button.disabled=true;button.textContent="Translating…";button.setAttribute("aria-busy","true");setStatus("Translating…");try{const japanese=await translate(english,settings);resetSession();current=ensureSchedule(createSentence(english,japanese));await saveSentence(current);renderSentence();setStatus("Ready to practice.")}catch(error){setStatus(error.message||"Translation failed.",true)}finally{button.disabled=false;button.textContent=label;button.removeAttribute("aria-busy")}}
function setStatus(message,error=false){$("#status").textContent=message;$("#status").classList.toggle("error",error)}
function populateVoices(){voices=japaneseVoices();const select=$("#voice"),previous=settings.voice;select.replaceChildren(...voices.map((voice,index)=>{const option=new Option(voice.name+" ("+voice.lang+")",String(index));option.selected=previous===String(index);return option}));$("#voice-warning").hidden=voices.length>0;$("#play-pause").disabled=voices.length===0||!current}
function setupRecognition(){const recognition=recognitionFactory(),mic=$("#microphone");if(!recognition){mic.disabled=true;$("#voice-input-status").textContent="Voice input is unavailable in this browser. You can still type.";return}mic.onclick=()=>{$("#voice-input-status").textContent="Listening…";mic.classList.add("listening");try{recognition.start()}catch{}};recognition.onresult=event=>{$("#english-input").value=event.results[0][0].transcript;$("#voice-input-status").textContent="Transcript ready—check it, then translate."};recognition.onerror=event=>{const messages={"not-allowed":"Microphone permission is blocked. Enable it in your browser settings.","no-speech":"No speech was detected. Try again or type your sentence.","audio-capture":"No microphone is available."};$("#voice-input-status").textContent=messages[event.error]||"Voice input failed: "+event.error+"."};recognition.onend=()=>mic.classList.remove("listening")}
async function startReview(){const items=await listSentences(),scheduled=items.map(item=>ensureSchedule(item));await Promise.all(scheduled.filter((item,index)=>item!==items[index]).map(saveSentence));reviewQueue=dueSentences(scheduled);reviewIndex=0;showView("review");renderReview()}
function reviewJapanese(sentence){return settings.showPolite?(sentence.politeJapanese||sentence.japanese):(sentence.casualJapanese||sentence.japanese)}
function reviewPlainJapanese(sentence){return settings.showPolite?(sentence.plainPoliteJapanese||sentence.plainJapanese):(sentence.plainCasualJapanese||sentence.plainJapanese)}
function renderReview(){resetSession();const sentence=reviewQueue[reviewIndex],complete=!sentence;$("#review-panel").hidden=complete;$("#review-actions").hidden=true;$("#review-complete").hidden=!complete;$("#review-progress").textContent=complete?"":`${reviewIndex+1} / ${reviewQueue.length}`;if(complete)return;reviewRevealed=false;$("#review-japanese").innerHTML=rubyHtml(reviewJapanese(sentence));$("#review-panel").classList.toggle("hide-furigana",settings.showFurigana===false);$("#review-english").textContent=sentence.english;$("#review-english").hidden=true;$("#review-hint").hidden=false;$("#review-echo-count").textContent=String(Number(sentence.echoCount)||0);$("#review-card").focus()}
function revealReview(){if(!reviewQueue[reviewIndex]||reviewRevealed)return;reviewRevealed=true;$("#review-english").hidden=false;$("#review-hint").hidden=true;$("#review-actions").hidden=false}
function playReviewAudio(){const sentence=reviewQueue[reviewIndex];if(!sentence)return;if(loop.running){loop.togglePause();return}const voice=voices[Number($("#voice").value)]||voices[0];loop.play(reviewPlainJapanese(sentence)||reviewJapanese(sentence).replace(/【[^】]+】/g,""),{voice,rate:Number($("#rate").value)})}
async function rateReview(rating){const sentence=reviewQueue[reviewIndex];if(!sentence||!reviewRevealed)return;resetSession();const updated=reviewSentence(sentence,rating);await saveSentence(updated);if(current?.id===updated.id)current=updated;reviewQueue[reviewIndex]=updated;reviewIndex++;renderReview()}
async function exportHistory(){const data=exportBackup(await listSentences(),settings),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),link=Object.assign(document.createElement("a"),{href:url,download:"jp-echo-backup.json"});link.click();URL.revokeObjectURL(url)}
async function exportAnki(){const button=$("#export-anki"),items=await listSentences();button.disabled=true;button.textContent="Building deck…";$("#anki-status").textContent="Creating JP Echo.apkg on this device…";try{await downloadAnkiDeck(items);$("#open-anki").hidden=false;const launched=openAnki(true);$("#anki-status").textContent=launched?"JP Echo.apkg downloaded. Opening Anki… If it stays here, tap Open Anki.":"JP Echo.apkg downloaded. Open it from Downloads to import it into Anki."}catch(error){$("#anki-status").textContent=error.message||"Anki export failed."}finally{button.disabled=false;button.textContent="Export to Anki"}}
function openAnki(automatic=false){const android=/android/i.test(navigator.userAgent),ios=/iphone|ipad|ipod/i.test(navigator.userAgent);if(android){window.location.href="intent:#Intent;package=com.ichi2.anki;end";return true}if(ios){window.location.href="anki://";return true}if(!automatic)$("#anki-status").textContent="Open JP Echo.apkg from your Downloads folder to import it into Anki.";return false}
async function importHistory(file){if(!file)return;try{const backup=JSON.parse(await file.text());if(backup.schemaVersion!==1||!Array.isArray(backup.sentences))throw new Error("Unsupported backup.");const merged=mergeSentences(await listSentences(),backup.sentences);await replaceAll(merged);setStatus("Imported "+backup.sentences.length+" sentence(s).");renderHistory()}catch(error){setStatus(error.message||"Import failed.",true)}}
$("#history-button").onclick=()=>showView($("#history-view").hidden?"history":"main");$("#back").onclick=()=>showView("main");$("#translate").onclick=performTranslation;$("#english-input").onkeydown=event=>{if((event.metaKey||event.ctrlKey)&&event.key==="Enter")performTranslation()};$("#play-pause").onclick=()=>{if(!current)return;if(loop.running){loop.togglePause();return}const voice=voices[Number($("#voice").value)]||voices[0];loop.play(selectedPlainJapanese(),{voice,rate:Number($("#rate").value)})};$("#show-english").onchange=()=>{saveSettings();renderSentence()};$("#show-furigana").onchange=()=>{saveSettings();renderSentence()};$("#show-polite").onchange=()=>{resetSession();saveSettings();renderSentence()};$("#rate").oninput=()=>{const rate=Number($("#rate").value);$("#rate-value").textContent=rate.toFixed(1)+"×";resetSession();loop.setRate(rate)};$("#settings-button").onclick=()=>$("#settings-dialog").showModal();$("#close-settings").onclick=()=>{saveSettings();$("#settings-dialog").close()};$("#export-anki").onclick=exportAnki;$("#open-anki").onclick=()=>openAnki();$("#export").onclick=exportHistory;$("#import").onclick=()=>$("#import-file").click();$("#import-file").onchange=event=>importHistory(event.target.files[0]);
$("#start-review").onclick=startReview;$("#review-back").onclick=()=>showView("history");$("#review-done").onclick=()=>showView("history");$("#review-card").onclick=revealReview;$("#review-audio").onclick=playReviewAudio;$("#review-again").onclick=()=>rateReview("again");$("#review-ok").onclick=()=>rateReview("ok");
$("#settings-button").onclick=openSettings;$("#dismiss-settings").onclick=cancelSettings;$("#cancel-settings").onclick=cancelSettings;$("#install-app").onclick=installApp;$("#settings-dialog").addEventListener("cancel",resetSettingsForm);$("#settings-dialog").onclick=event=>{if(event.target===$("#settings-dialog"))cancelSettings()};$("#voice").onchange=resetSession;window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;updateInstallUI()});window.addEventListener("appinstalled",()=>{installPrompt=null;updateInstallUI()});
$("#history-search").oninput=renderHistory;for(const id of ["#history-filter","#history-order"]){$(id).onchange=()=>{settings.historyFilter=$("#history-filter").value;settings.historyOrder=$("#history-order").value;localStorage.setItem("jp-echo-settings",JSON.stringify(settings));renderHistory()}}
$("#api-key").value=settings.apiKey||"";$("#proxy-url").value=settings.proxyUrl||"";$("#rate").value=settings.rate||1;$("#rate-value").textContent=Number($("#rate").value).toFixed(1)+"×";$("#show-english").checked=settings.showEnglish??false;$("#show-furigana").checked=settings.showFurigana??true;$("#show-polite").checked=settings.showPolite??false;$("#history-filter").value=settings.historyFilter||"all";$("#history-order").value=settings.historyOrder||"newest";speechSynthesis.onvoiceschanged=populateVoices;populateVoices();setupRecognition();updateInstallUI();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");
