// EPUB ZIP extraction uses browser-native raw DEFLATE; only spine XHTML is read.
export function zipDirectory(buffer){
 const bytes=new Uint8Array(buffer),view=new DataView(buffer);if(bytes.length>100*1024*1024)throw Error('Use an EPUB smaller than 100 MB.');let end=-1;
 for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){end=i;break}
 if(end<0)throw Error('This file is not a valid EPUB ZIP archive.');if(view.getUint16(end+4,true)||view.getUint16(end+6,true))throw Error('Multipart EPUB archives are not supported.');
 const count=view.getUint16(end+10,true),entries=new Map();let offset=view.getUint32(end+16,true),total=0;
 for(let i=0;i<count;i++){if(offset+46>bytes.length||view.getUint32(offset,true)!==0x02014b50)throw Error('The EPUB directory is damaged.');const length=view.getUint16(offset+28,true),extra=view.getUint16(offset+30,true),comment=view.getUint16(offset+32,true),name=new TextDecoder().decode(bytes.slice(offset+46,offset+46+length)),size=view.getUint32(offset+24,true);total+=size;if(total>200*1024*1024||count>20000)throw Error('This EPUB expands beyond the supported size.');entries.set(name,{name,method:view.getUint16(offset+10,true),flags:view.getUint16(offset+8,true),size,compressed:view.getUint32(offset+20,true),offset:view.getUint32(offset+42,true)});offset+=46+length+extra+comment;}return entries;
}
export function epubPath(base,href){if(/^[a-z]+:|^\/|\\/i.test(href))throw Error('External EPUB resources are not supported.');const parts=base.split('/').slice(0,-1);for(const part of decodeURIComponent(href.split('#')[0]).split('/')){if(part==='..'){if(!parts.length)throw Error('Invalid EPUB resource path.');parts.pop()}else if(part&&part!=='.')parts.push(part)}return parts.join('/')}
export async function readEpub(buffer,{parseXML=text=>new DOMParser().parseFromString(text,'application/xml'),parseHTML=text=>new DOMParser().parseFromString(text,'text/html'),inflate=async (bytes,expected)=>{try{const reader=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader(),chunks=[];let total=0;for(;;){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>expected){await reader.cancel();throw Error('Expanded chapter exceeds its declared size.')}chunks.push(value)}const result=new Uint8Array(total);let offset=0;for(const chunk of chunks){result.set(chunk,offset);offset+=chunk.length}return result}catch{throw Error('Your browser could not decompress this EPUB. Try a current browser or an unencrypted EPUB.')}}}={}){
 const entries=zipDirectory(buffer),bytes=new Uint8Array(buffer),view=new DataView(buffer);
 async function read(path){const entry=entries.get(path);if(!entry)throw Error(`Missing EPUB resource: ${path}`);if(entry.flags&1)throw Error('Encrypted EPUBs cannot be imported.');if(entry.offset+30>bytes.length||view.getUint32(entry.offset,true)!==0x04034b50)throw Error('Damaged EPUB chapter.');const start=entry.offset+30+view.getUint16(entry.offset+26,true)+view.getUint16(entry.offset+28,true);if(start+entry.compressed>bytes.length)throw Error('Truncated EPUB chapter.');const compressed=bytes.slice(start,start+entry.compressed),data=entry.method===0?compressed:entry.method===8?await inflate(compressed,entry.size):null;if(!data||data.length!==entry.size)throw Error('Unsupported or damaged EPUB compression.');return new TextDecoder().decode(data)}
 const container=parseXML(await read('META-INF/container.xml'));const root=container.getElementsByTagNameNS('*','rootfile')[0]?.getAttribute('full-path');if(!root)throw Error('The EPUB has no package document.');const packageDoc=parseXML(await read(root));if(packageDoc.getElementsByTagName('parsererror').length)throw Error('The EPUB package is invalid.');const manifest=new Map([...packageDoc.getElementsByTagNameNS('*','item')].map(node=>[node.getAttribute('id'),node]));const chapters=[];
 for(const item of packageDoc.getElementsByTagNameNS('*','itemref')){if(item.getAttribute('linear')==='no')continue;const resource=manifest.get(item.getAttribute('idref'));if(!resource||!['application/xhtml+xml','text/html'].includes(resource.getAttribute('media-type')))continue;const path=epubPath(root,resource.getAttribute('href')),document=parseHTML(await read(path));document.querySelectorAll('script,style,rt,rp,nav').forEach(node=>node.remove());document.querySelectorAll('p,div,h1,h2,h3,li,br').forEach(node=>node.append(document.createTextNode('\n')));const text=(document.body?.textContent||'').replace(/[ \t]+/g,' ').replace(/\n\s*\n/g,'\n').trim();if(text)chapters.push({path,title:document.querySelector('h1,h2,title')?.textContent.trim()||`Chapter ${chapters.length+1}`,text})}
 if(!chapters.length)throw Error('No readable chapters found. Image-only or DRM-protected EPUBs cannot be imported.');return {title:packageDoc.getElementsByTagNameNS('*','title')[0]?.textContent.trim()||'EPUB book',chapters};
}
