export class ShadowLoop{
  constructor({onEcho,onState,setTimer=(callback,delay)=>window.setTimeout(callback,delay),clearTimer=timer=>window.clearTimeout(timer),now=()=>window.performance.now()}){this.onEcho=onEcho;this.onState=onState;this.setTimer=setTimer;this.clearTimer=clearTimer;this.now=now;this.running=false;this.paused=false;this.timer=null;this.timerCallback=null;this.timerStarted=0;this.remaining=0;this.utterance=null;this.rate=1;this.cycle=0;this.phase="stopped"}
  schedule(callback,delay){this.timerCallback=callback;this.remaining=delay;this.timerStarted=this.now();this.timer=this.setTimer(()=>{this.timer=null;this.timerCallback=null;callback()},delay)}
  play(text,{voice,rate=1}){this.stop(false);this.running=true;this.rate=rate;const cycle=++this.cycle;const speak=()=>{if(!this.running||this.paused||cycle!==this.cycle)return;const utterance=new SpeechSynthesisUtterance(text),started=this.now();this.utterance=utterance;this.phase="speaking";utterance.lang="ja-JP";utterance.voice=voice||null;utterance.rate=this.rate;utterance.onstart=()=>{if(cycle===this.cycle)this.onState("speaking")};utterance.onerror=event=>{if(cycle!==this.cycle)return;this.utterance=null;if(event.error!=="canceled")this.onState("error");this.running=false};utterance.onend=()=>{if(!this.running||cycle!==this.cycle)return;this.utterance=null;this.onEcho();const duration=Math.max(900,this.now()-started);this.phase="imitate";this.onState("imitate");this.schedule(speak,duration+500)};speechSynthesis.speak(utterance)};speak()}
  setRate(rate){this.rate=rate;return this.rate}
  togglePause(){if(!this.running)return false;if(this.paused){this.paused=false;if(this.utterance)speechSynthesis.resume();else if(this.timerCallback)this.schedule(this.timerCallback,this.remaining);this.onState(this.phase==="imitate"?"imitate":"speaking")}else{this.paused=true;if(this.utterance)speechSynthesis.pause();if(this.timer){this.remaining=Math.max(0,this.remaining-(this.now()-this.timerStarted));this.clearTimer(this.timer);this.timer=null}this.onState("paused")}return this.paused}
  stop(notify=true){this.running=false;this.paused=false;this.phase="stopped";this.cycle++;this.clearTimer(this.timer);this.timer=null;this.timerCallback=null;this.remaining=0;if(this.utterance){this.utterance.onstart=null;this.utterance.onend=null;this.utterance.onerror=null;this.utterance=null}speechSynthesis.cancel();if(notify)this.onState("stopped")}
}
export function japaneseVoices(){return speechSynthesis.getVoices().filter(voice=>voice.lang.toLowerCase().startsWith("ja"))}
export function recognitionFactory(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return null;const recognition=new Recognition();recognition.lang="en-US";recognition.interimResults=false;recognition.maxAlternatives=1;return recognition}
