export class ShadowLoop{
  constructor({onEcho,onState,setTimer=(callback,delay)=>window.setTimeout(callback,delay),clearTimer=timer=>window.clearTimeout(timer),now=()=>window.performance.now()}){this.onEcho=onEcho;this.onState=onState;this.setTimer=setTimer;this.clearTimer=clearTimer;this.now=now;this.running=false;this.paused=false;this.timer=null;this.utterance=null;this.rate=1;this.cycle=0}
  play(text,{voice,rate=1}){this.stop(false);this.running=true;this.rate=rate;const cycle=++this.cycle;const speak=()=>{if(!this.running||cycle!==this.cycle)return;const utterance=new SpeechSynthesisUtterance(text),started=this.now();this.utterance=utterance;utterance.lang="ja-JP";utterance.voice=voice||null;utterance.rate=this.rate;utterance.onstart=()=>{if(cycle===this.cycle)this.onState("speaking")};utterance.onerror=event=>{if(cycle!==this.cycle)return;this.utterance=null;if(event.error!=="canceled")this.onState("error");this.running=false};utterance.onend=()=>{if(!this.running||cycle!==this.cycle)return;this.utterance=null;this.onEcho();const duration=Math.max(900,this.now()-started);this.onState("imitate");this.timer=this.setTimer(speak,duration+500)};speechSynthesis.speak(utterance)};speak()}
  setRate(rate){this.rate=rate;if(this.paused){speechSynthesis.resume();this.paused=false;this.onState("speaking")}return this.rate}
  togglePause(){if(!this.running)return false;if(this.paused)speechSynthesis.resume();else speechSynthesis.pause();this.paused=!this.paused;this.onState(this.paused?"paused":"speaking");return this.paused}
  stop(notify=true){this.running=false;this.paused=false;this.cycle++;this.clearTimer(this.timer);this.timer=null;if(this.utterance){this.utterance.onstart=null;this.utterance.onend=null;this.utterance.onerror=null;this.utterance=null}speechSynthesis.cancel();if(notify)this.onState("stopped")}
}
export function japaneseVoices(){return speechSynthesis.getVoices().filter(voice=>voice.lang.toLowerCase().startsWith("ja"))}
export function recognitionFactory(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return null;const recognition=new Recognition();recognition.lang="en-US";recognition.interimResults=false;recognition.maxAlternatives=1;return recognition}
